<a href="https://colab.research.google.com/github/rishabhk1501/Data-Analytics-Tasks/blob/main/session_19_tasks_soln.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [2]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

In [3]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

In [4]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
titanic_df[titanic_df['Embarked'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [7]:
# code here

pclass = titanic_df.groupby('Pclass')
pclass['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [8]:
titanic_df['Pclass'].unique()

array([3, 1, 2])

In [9]:
l = []
for group,data in pclass:
  df = pd.DataFrame(columns=['Class','total_null_values'])
  df.loc[0,'Class'] = group
  df.loc[0,'total_null_values'] = data['Age'].isnull().sum()
  l.append(df)
pd.concat(l).set_index('Class')

      total_null_values
Class
1                    30
2                    11
3                   136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [10]:
# code here
l = []
for group,data in pclass:
  data['Embarked'].fillna(data['Embarked'].value_counts().index[0], inplace=True)


  l.append(data)

titanic_df = pd.concat(l)

In [11]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [12]:
# code here

embarked = titanic_df.groupby('Embarked')

In [13]:
embarked.groups.keys()

dict_keys(['C', 'Q', 'S'])

In [14]:
l1 = []
for group,data in embarked:
  l1.append(group)
l1

['C', 'Q', 'S']

In [15]:
l2 = []
for group,data in embarked:
  pclass = data.groupby('Pclass')
  pclass_list = list(pclass.groups.keys())
  mean_fare_list = list(round(pclass['Fare'].mean(),2))
  dic = dict(zip(pclass_list,mean_fare_list))
  l2.append(dic)


l2

[{1: 104.72, 2: 25.36, 3: 11.21},
 {1: 90.0, 2: 12.35, 3: 11.18},
 {1: 70.51, 2: 20.33, 3: 14.64}]

In [16]:
final = dict(zip(l1,l2))
final

{'C': {1: 104.72, 2: 25.36, 3: 11.21},
 'Q': {1: 90.0, 2: 12.35, 3: 11.18},
 'S': {1: 70.51, 2: 20.33, 3: 14.64}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [17]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

In [18]:
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [19]:
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,0,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,0,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,0,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,0,19,4,516,419,24,3,5,28,4,0

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [20]:
# code here

column_to_perform = ['Passes', 'Passes Completed', 'Attempted Line Breaks', 'Completed Line Breaks']
team = fifa_df.groupby('Team')

In [21]:
def normalization(group,list_column):
  for i in range(len(list_column)):
    group['Normalized' + ' ' + list_column[i]] = (group[list_column[i]] - group[list_column[i]].mean())/(group[list_column[i]].std())

  return group

In [22]:
team.apply(normalization,column_to_perform)

               Sl. No  Match No.       Team        Against Group  Goal  \
Team
Argentina 8         9          5  Argentina   Saudi Arabia     C     1
          46       47         24  Argentina         Mexico     C     2
          77       78         39  Argentina         Poland     C     2
          98       99         50  Argentina      Australia     C     2
          115     116         58  Argentina    Netherlands     C     2
...               ...        ...        ...            ...   ...   ...
Uruguay   63       64         32    Uruguay       Portugal     H     0
          89       90         45    Uruguay          Ghana     H     2
Wales     7         8          4      Wales  United States     B     1
          32       33         17      Wales           Iran     B     0
          68       69         35      Wales        England     B     0

               Possession (%)  Inside Penalty Area  Outside Penalty Area  \
Team
Argentina 8                51                    1                     0
          46               50                    1                     1
          77               67                    1                     1
          98               53                    2                     0
          115              44                    2                     0
...                       ...                  ...                   ...
Uruguay   63               35                    0                     0
          89               39                    2                     0
Wales     7                39                    1                     0
          32               51                    0                     0
          68               33                    0                     0

               Assists  Total Attempts  On Target  Off Target  \
Team
Argentina 8          0              14          6           6
          46         2               5          2           3
          77         2              25         13           8
          98         1              14          5           7
          115        1              15          6           8
...                ...             ...        ...         ...
Uruguay   63         0              10          3           6
          89         1              12          7           5
Wales     7          0               7          3           3
          32         0              10          3           4
          68         0               7          1           3

               Target in Penalty  Target from Outside  Left Channel  \
Team
Argentina 8                   10                    4            12
          46                   2                    3            10
          77                  10                   15            25
          98                  11                    3            15
          115                  5                   10             7
...                          ...                  ...           ...
Uruguay   63                   6                    4            13
          89                   7                    5             7
Wales     7                    5                    2             7
          32                   5                    5            18
          68                   1                    6             7

               Left Inside Channel  Central Channel  Right Inside Channel  \
Team
Argentina 8                      4                5                     8
          46                     6                2                     4
          77                     8                7                    10
          98                     6               11                     2
          115                    7               13                     6
...                            ...              ...                   ...
Uruguay   63                     8                4                     5
          89                     2               13                     3
Wales     7                      2                5                     2
          32                     3                8                    11
          68                     1                2                     0

               Right Channel  Receptions MD  Receptions D  \
Team
Argentina 8               18             91            27
          46              12             89             2
          77              26            150            36
          98              17            127             8
          115             17            104             7
...                      ...            ...           ...
Uruguay   63               9             94             6
          89              17            186            14
Wales     7                7             73             9
          32              13            101            13
          68               4             46             1

               Attempted Line Breaks  Completed Line Breaks  \
Team
Argentina 8                      195                    127
          46                     150                    100
          77                     141                    126
          98                     181                    135
          115                    203                    122
...                              ...                    ...
Uruguay   63                     150                     86
          89                     186                    124
Wales     7                      174                    103
          32                     208                    129
          68                     104                     55

               Attempted Defensive Line Breaks  \
Team
Argentina 8                                 10
          46                                10
          77                                20
          98                                16
          115                               24
...                                        ...
Uruguay   63                                17
          89                                24
Wales     7                                 17
          32                                17
          68                                 4

               Completed Defensive Line Breaks  Yellow Cards  Red Cards  \
Team
Argentina 8                                  8             0          0
          46                                 5             1          0
          77                                16             1          0
          98                                 8             0          0
          115                                8             8          0
...                                        ...           ...        ...
Uruguay   63                                11             2          0
          89                                14             3          0
Wales     7                                  8             2          0
          32                                 8             1          1
          68                                 1             2          0

               Fouls Against  Offsides  Passes  Passes Completed  Crosses  \
Team
Argentina 8                7        10     593               525       36
          46              15         2     533               464       14
          77              11         0     862               814       22
          98               8         4     711               635        6
          115             18         2     603               511       16
...                      ...       ...     ...               ...      ...
Uruguay   63              16         0     390               306       18
          89              11         2     446               361       15
Wales     7               10         1     409               321       15
          32               9         2     508               413       20
          68              16         1     325               261        4

               Crosses Completed  Corners  Free Kicks  Penalties Scored  Pts  \
Team
Argentina 8                   15        9          21                 1    0
          46                   2        4          23                 0    3
          77                   5        9           5                 0    3
          98                   1        1          15                 0    3
          115                  4        8          30                 5    3
...                          ...      ...         ...               ...  ...
Uruguay   63                   5        2          13                 0    0
          89                   4        2          20                 0    3
Wales     7                    6        3          15                 1    1
          32                   5        2          12                 0    1
          68                   1        1          10                 0    0

               Normalized Passes  Normalized Passes Completed  \
Team
Argentina 8            -0.208138                    -0.157888
          46           -0.630447                    -0.574048
          77            1.685214                     1.813757
          98            0.622403                     0.592566
          115          -0.137753                    -0.253400
...                          ...                          ...
Uruguay   63           -0.931702                    -0.894617
          89           -0.124867                    -0.184945
Wales     7            -0.054584                    -0.139325
          32            1.026174                     1.062357
          68           -0.971590                    -0.923031

               Normalized Attempted Line Breaks  \
Team
Argentina 8                            0.364745
          46                          -0.795806
          77                          -1.027917
          98                           0.003684
          115                          0.571065
...                                         ...
Uruguay   63                          -0.484182
          89                           1.149932
Wales     7                            0.226294
          32                           0.867461
          68                          -1.093756

               Normalized Completed Line Breaks
Team
Argentina 8                            0.087403
          46                          -0.945040
          77                           0.049164
          98                           0.393311
          115                         -0.103791
...                                         ...
Uruguay   63                          -0.623480
          89                           1.153437
Wales     7                            0.195342
          32                           0.887916
          68                          -1.083258

[128 rows x 42 columns]

In [23]:
team.agg({'Passes': ['min', 'max'], 'Yellow Cards': ['min', 'max', 'mean'], 'Attempted Line Breaks': ['min', 'max', 'std'], 'Possession (%)': ['mean']})

              Passes      Yellow Cards               Attempted Line Breaks  \
                 min  max          min max      mean                   min
Team
Argentina        408  862            0   8  2.285714                   141
Australia        286  466            0   3  1.750000                   133
Belgium          512  685            1   3  1.666667                   167
Brazil           548  695            0   3  1.200000                   164
Cameroon         295  500            1   5  2.666667                   144
...              ...  ...          ...  ..       ...                   ...
Switzerland      403  512            1   4  2.250000                   157
Tunisia          328  501            1   3  1.666667                   153
United States    427  572            0   4  1.250000                   143
Uruguay          390  528            1   3  2.000000                   146
Wales            325  508            1   2  1.666667                   104

                              Possession (%)
               max        std           mean
Team
Argentina      249  38.774685      49.285714
Australia      171  17.682383      31.250000
Belgium        195  14.422205      49.000000
Brazil         193  10.691118      50.400000
Cameroon       182  19.857828      38.333333
...            ...        ...            ...
Switzerland    178   9.032349      43.000000
Tunisia        200  24.419937      38.666667
United States  204  27.693260      47.000000
Uruguay        186  22.030282      41.000000
Wales          208  53.028294      41.000000

[32 rows x 9 columns]

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

In [24]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

In [25]:
ipl = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTqg6_lfIjClM068CGyvqBVXMqlhRCRNM1ZpmitVDSOmznbjnZc_EFQ_tJtshdULUZBy0zEC6YoC7dp/pub?output=csv')

In [26]:
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [27]:
batsman_chasing = ipl[ipl['innings'] == 2].groupby('batter')

In [28]:
# code here
batsman_chasing['batsman_run'].sum().sort_values(ascending=False).head(1)

batter
V Kohli    3070
Name: batsman_run, dtype: int64

In [29]:
ipl['extra_type'].unique()

array([nan, 'legbyes', 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [30]:
df = ipl[~(ipl['extra_type'].isin(['noballs', 'wides', 'byes']))]

In [31]:
valid_balls = df[df['innings'] == 2]

In [32]:
batsman_sr = valid_balls.groupby('batter')

In [33]:
((batsman_sr['batsman_run'].sum()/batsman_sr['batsman_run'].size())*100).sort_values(ascending=False)

batter
PN Mankad          400.000000
OF Smith           312.500000
KMDN Kulasekara    250.000000
B Stanlake         250.000000
Shahid Afridi      234.782609
                      ...
IC Pandey            0.000000
GC Viljoen           0.000000
U Kaul               0.000000
DE Bollinger         0.000000
M Ntini              0.000000
Name: batsman_run, Length: 552, dtype: float64

In [34]:
batsman_sr['batsman_run'].size().sort_values(ascending=False)

batter
V Kohli          2358
S Dhawan         2128
RV Uthappa       2094
G Gambhir        2040
RG Sharma        1999
                 ...
SJ Srivastava       1
AN Ghosh            1
RV Gomez            1
KJ Abbott           1
SB Wagh             1
Name: batsman_run, Length: 552, dtype: int64

In [35]:
batsman_sr['batsman_run'].sum()

batter
A Ashish Reddy     114
A Badoni            55
A Chopra             2
A Choudhary         10
A Flintoff          40
                  ...
YV Takawale        130
Yashpal Singh       34
Younis Khan          3
Yuvraj Singh      1234
Z Khan              56
Name: batsman_run, Length: 552, dtype: int64

In [36]:
runs_scored = batsman_sr['batsman_run'].sum().reset_index()
balls_faced = batsman_sr['batsman_run'].size().reset_index()

In [37]:
chasing = runs_scored.merge(balls_faced,how='inner',on='batter')

In [38]:
chasing.rename(columns={'batsman_run_x': 'runs_scored','batsman_run_y':'balls_faced'},inplace=True)

In [39]:
chasing.set_index('batter',inplace=True)

In [40]:
final = chasing[chasing['balls_faced'] > 100]

In [41]:
final

                 runs_scored  balls_faced
batter
A Mishra                 216          223
A Symonds                352          289
AB de Villiers          1992         1445
AC Gilchrist            1109          748
AD Mathews               313          262
...                      ...          ...
Y Venugopal Rao          463          375
YBK Jaiswal              259          181
YK Pathan               1874         1229
YV Takawale              130          118
Yuvraj Singh            1234         1027

[178 rows x 2 columns]

In [42]:
def strike_rate(row):
  scored = row.loc['runs_scored']
  deliveries = row.loc['balls_faced']

  return round(((scored/deliveries)*100),2)

In [43]:
final['chasing_strike_rate'] = final.apply(strike_rate,axis=1)

<ipython-input-43-5bc0ab25e0c6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['chasing_strike_rate'] = final.apply(strike_rate,axis=1)

In [45]:
final.sort_values('chasing_strike_rate',ascending=False).head(1)

            runs_scored  balls_faced  chasing_strike_rate
batter
PJ Cummins          220          112               196.43

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [46]:
ipl['kind'].unique()

array([nan, 'caught', 'caught and bowled', 'run out', 'bowled', 'stumped',
       'lbw', 'hit wicket', 'retired hurt', 'retired out',
       'obstructing the field'], dtype=object)

In [47]:
df = ipl[(ipl['isWicketDelivery'] == 1) & (ipl['kind'].isin(['caught', 'caught and bowled', 'bowled', 'stumped', 'lbw', 'hit wicket']))]

In [48]:
# code here

bat_bowl = df.groupby(['batter', 'bowler'])

In [49]:
a = bat_bowl.size().sort_values(ascending=False).reset_index()
a

          batter          bowler  0
0     RV Uthappa        R Ashwin  7
1       MS Dhoni          Z Khan  7
2        V Kohli  Sandeep Sharma  7
3      RG Sharma       SP Narine  7
4      RG Sharma        A Mishra  7
...          ...             ... ..
8056    JR Hopes       JA Morkel  1
8057    JR Hopes   Iqbal Abdulla  1
8058    JR Hopes        DJ Bravo  1
8059    JR Hopes        AB Dinda  1
8060      Z Khan        SK Warne  1

[8061 rows x 3 columns]

In [50]:
runs_conceded = ipl.groupby(['batter','bowler'])

In [51]:
b = runs_conceded['batsman_run'].sum().sort_values(ascending=False).reset_index()
b

            batter       bowler  batsman_run
0        DA Warner    SP Narine          176
1         SK Raina    PP Chawla          175
2          V Kohli     R Ashwin          160
3          V Kohli     A Mishra          158
4          V Kohli     DJ Bravo          157
...            ...          ...          ...
24208  JP Faulkner  CJ Anderson            0
24209    IK Pathan  Kamran Khan            0
24210     S Nadeem    JA Morkel            0
24211     S Nadeem     HV Patel            0
24212     R Bhatia      SW Tait            0

[24213 rows x 3 columns]

In [52]:
final = pd.merge(a,b,how='inner',on=['batter','bowler']).rename(columns={0:'total_dismissals', 'batsman_run':'runs_conceded'})

In [53]:
final = final.sort_values(['total_dismissals','runs_conceded'],ascending=[False,True])

In [54]:
final = final.drop_duplicates('batter')

In [55]:
final

             batter          bowler  total_dismissals  runs_conceded
1          MS Dhoni          Z Khan                 7             74
2           V Kohli  Sandeep Sharma                 7             78
4         RG Sharma        A Mishra                 7             87
0        RV Uthappa        R Ashwin                 7            123
7         Q de Kock       YS Chahal                 6             44
...             ...             ...               ...            ...
7469      GR Napier        CH Gayle                 1             10
4160      SB Jakati       DP Nannes                 1             11
6432        M Ntini   Sohail Tanvir                 1             11
5865     Avesh Khan     Rashid Khan                 1             12
7217  Iqbal Abdulla        DJ Bravo                 1             16

[554 rows x 4 columns]

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [56]:
def batting_pair(row):

  a = row.loc['batter']
  b = row.loc['non-striker']

  pair = frozenset({a,b})

  return pair

In [57]:
ipl['batting_pair'] = ipl.apply(batting_pair,axis=1)

In [58]:
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,batting_pair
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(YBK Jaiswal, JC Buttler)"
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(YBK Jaiswal, JC Buttler)"
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(YBK Jaiswal, JC Buttler)"
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(YBK Jaiswal, JC Buttler)"
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,"(YBK Jaiswal, JC Buttler)"

In [59]:
pair = ipl.groupby('batting_pair')

In [60]:
final = pair['batsman_run'].sum().sort_values(ascending=False)

In [61]:
final.head(10)

batting_pair
(AB de Villiers, V Kohli)    3040
(CH Gayle, V Kohli)          2650
(DA Warner, S Dhawan)        2242
(G Gambhir, RV Uthappa)      1795
(KL Rahul, MA Agarwal)       1664
(CH Gayle, KL Rahul)         1573
(SK Raina, MS Dhoni)         1427
(PP Shaw, S Dhawan)          1423
(DA Warner, JM Bairstow)     1336
(RR Pant, SS Iyer)           1319
Name: batsman_run, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

In [71]:
pair = ipl.groupby('batting_pair')

In [72]:
l = []

for group,data in pair:
  df = pd.DataFrame(index=[group],columns=['Runs', 'Avg', 'StrikeRate'])

  df['Runs'] = data['batsman_run'].sum()
  df['Avg'] = round((data['batsman_run'].sum()) / (data['ID'].nunique()),2)
  df['StrikeRate'] = (round((data['batsman_run'].sum()) / (len(data)),2)) * 100

  l.append(df)

final = pd.concat(l)
final

                                     Runs    Avg  StrikeRate
(YBK Jaiswal, JC Buttler)             366  24.40       120.0
(DPMD Jayawardene, Y Venugopal Rao)    85  14.17        98.0
(Y Venugopal Rao, P Negi)              11   5.50        73.0
(Sunny Gupta, P Negi)                   8   8.00       133.0
(VR Aaron, P Negi)                      0   0.00         0.0
...                                   ...    ...         ...
(Shivam Mavi, MG Johnson)               8   8.00        80.0
(HH Pandya, A Dananjaya)                2   2.00        50.0
(M Markande, A Dananjaya)               6   6.00       120.0
(RR Pant, G Gambhir)                   42  21.00       145.0
(P Kumar, AA Noffke)                   12  12.00        86.0

[4259 rows x 3 columns]

In [73]:
final = final.reset_index()
final

                                    index  Runs    Avg  StrikeRate
0               (YBK Jaiswal, JC Buttler)   366  24.40       120.0
1     (DPMD Jayawardene, Y Venugopal Rao)    85  14.17        98.0
2               (Y Venugopal Rao, P Negi)    11   5.50        73.0
3                   (Sunny Gupta, P Negi)     8   8.00       133.0
4                      (VR Aaron, P Negi)     0   0.00         0.0
...                                   ...   ...    ...         ...
4254            (Shivam Mavi, MG Johnson)     8   8.00        80.0
4255             (HH Pandya, A Dananjaya)     2   2.00        50.0
4256            (M Markande, A Dananjaya)     6   6.00       120.0
4257                 (RR Pant, G Gambhir)    42  21.00       145.0
4258                 (P Kumar, AA Noffke)    12  12.00        86.0

[4259 rows x 4 columns]

In [78]:
list(final.loc[0,'index'])[0]

'YBK Jaiswal'

In [79]:
final['Batter 1'] = final['index'].apply(lambda x: list(x)[0])
final['Batter 2'] = final['index'].apply(lambda x: list(x)[1])

In [81]:
final = final.drop(columns=['index'])

In [83]:
final = final[['Batter 1', 'Batter 2', 'Runs', 'Avg', 'StrikeRate']]

In [86]:
final.sort_values('Runs',ascending=False)

            Batter 1    Batter 2  Runs    Avg  StrikeRate
2545  AB de Villiers     V Kohli  3040  39.48       148.0
4054        CH Gayle     V Kohli  2650  44.17       134.0
4036       DA Warner    S Dhawan  2242  44.84       130.0
4029       G Gambhir  RV Uthappa  1795  37.40       126.0
2998        KL Rahul  MA Agarwal  1664  50.42       137.0
...              ...         ...   ...    ...         ...
1310        RP Singh   RJ Harris     0   0.00         0.0
238        SP Narine    L Balaji     0   0.00         0.0
617         R Dhawan    L Balaji     0   0.00         0.0
3132        M Ashwin    TS Mills     0   0.00         0.0
3720        HV Patel   STR Binny     0   0.00         0.0

[4259 rows x 5 columns]